default: --format pretty --strict --tags ~@wip --tags ~@general_agency_enabled --tags ~@quoting_enabled --tags ~@edit_aptc --tags  ~@more_than_sole_source --tags ~@individual_enabled -r features --profile semaphoreci
wip: --tags @wip:11 --wip features
rerun: -format rerun --out rerun.txt --strict --tags ~@wip
first_rerun: --format 'pretty' --format rerun --out tmp/cucumber_failures_2.log
second_rerun: --format 'pretty' --format rerun --out tmp/cucumber_failures_3.log
screenshots: -r features SCREENSHOTS=true
semaphoreci: --format rerun --out rerun.txt --format json --out=cucumber_report.json
