---
registry:
  - namespace:
      - :features
    features:
      - key: :enroll_app
        is_enabled: true
        meta:
          label: Enroll Application
          content_type: :boolean
          default: true
          value: true
          description: The Enroll Application enables customers to register and enroll in products, including determining eligibility, shopping for products, calculating premiums, and securely managing their personal information
          is_required: true
          is_visible: true
        settings:
          - key: :copyright_period_start
            item: "2013"
          - key: :policies_url
            item: "https://dchealthlink.com/"
          - key: :faqs_url
            item: "https://www.dchealthlink.com/Frequently-Asked-Questions"
          - key: :help_url
            item: "https://www.dchealthlink.com/help"
          - key: :business_resource_center_url
            item: "https://www.mahealthconnector.org/business/business-resource-center"
          - key: :nondiscrimination_notice_url
            item: "https://www.dchealthlink.com/nondiscrimination"
      - key: :employee_roster_updates
        is_enabled: true
      - key: :continuous_plan_shopping
        is_enabled: true
      - key: display_estimated_employee_costs
        is_enabled: true
      - key: :admin_issuers_tab_display
        is_enabled: <%= ENV['ADMIN_ISSUERS_TAB_DISPLAY_IS_ENABLED'] || false %>
      - key: :admin_products_tab_display
        is_enabled: <%= ENV['ADMIN_PRODUCTS_TAB_DISPLAY_IS_ENABLED'] || false %>
